/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DotProduct */

#ifndef _Included_DotProduct
#define _Included_DotProduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DotProduct
 * Method:    CalculateDotProduct1
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)D
 */
JNIEXPORT jdouble JNICALL Java_DotProduct_CalculateDotProduct1
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     DotProduct
 * Method:    CalculateDotProduct2
 * Signature: ([Ljava/lang/Double;)D
 */
JNIEXPORT jdouble JNICALL Java_DotProduct_CalculateDotProduct2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     DotProduct
 * Method:    CalculateDotProduct3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DotProduct_CalculateDotProduct3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
